/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.grafoproyecto;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.IOException;

/**
 *
 * @author malej
 */
public class Ventanamodificada extends javax.swing.JFrame {
    

    /**
     * Creates new form Ventana
     */
    public Ventanamodificada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFileChooser selectorArchivos = new JFileChooser();
    selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int ventanaBusqueda = selectorArchivos.showOpenDialog(this);  
    if (ventanaBusqueda == JFileChooser.APPROVE_OPTION){
        File archivoSeleccionado = selectorArchivos.getSelectedFile();
        //Validacion .txt
        if (archivoSeleccionado.getName().toLowerCase().endsWith(".txt")){     
            //Aviso de carga y carga 
            if(ControladorGrafos.getGrafoActual()!= null){
            int confirmacion = JOptionPane.showConfirmDialog(this, "Se cargara un nuevo grafo, este archivo remplazara a los anteriores.", 
            "Advertencia de Sobrescritura",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if (confirmacion == JOptionPane.YES_OPTION){ 
                try {
                    ControladorGrafos.CargarGrafo(archivoSeleccionado);
                    JOptionPane.showMessageDialog(this, "Grafo cargado exitosamente.");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage(), "Error de Carga", JOptionPane.ERROR_MESSAGE);
                }
            }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Su archivo debe ser de tipo .txt",
                    "Error de Formato", JOptionPane.WARNING_MESSAGE);                     
            }                                     
    }//GEN-LAST:event_jButton1ActionPerformed
}

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
