/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.grafoproyecto;

//Imports para la ventana y componentes de Swing 
import javax.swing.JFrame;
import java.awt.BorderLayout;

//Imports para la estructura de datos del grafo (JGraphT) 
import org.jgrapht.graph.DefaultDirectedGraph;
import org.jgrapht.graph.DefaultEdge;
import org.jgrapht.ListenableGraph;
import org.jgrapht.graph.DefaultListenableGraph;

//Imports para la visualizacion del grafo (JGraphX) 
import org.jgrapht.ext.JGraphXAdapter;
import com.mxgraph.layout.mxCircleLayout;
import com.mxgraph.swing.mxGraphComponent;


/**
 *
 * @author samir
 */
public class VisualGrafo extends javax.swing.JFrame {
      // 1. Añade una variable para guardar el objeto Grafo
    private Grafo grafo;

    // 2. Modifica el constructor para aceptar el objeto Grafo
    public VisualGrafo(Grafo grafo) {
        this.grafo = grafo; // Guarda el grafo en la variable de clase
        initComponents();
        inicializarVisualizacion(); 
    }
    
    // 4. (Nuevo Método) Aquí es donde irá la lógica de dibujo
    private void inicializarVisualizacion() {
        // Por ahora, solo añade un mensaje temporal, 
        // hasta que instalemos JGraphX para el dibujo real.
         // 1. Mapear tu objeto 'Grafo' (personal) a la estructura de JGraphT
        ListenableGraph<String, DefaultEdge> g = new DefaultListenableGraph<>(new DefaultDirectedGraph<>(DefaultEdge.class));
    
    // **********************************************
    // LÓGICA DE CONVERSIÓN
    // **********************************************
    
    // 1. Añadir Nodos (Usuarios)
    for (Usuario u : this.grafo.getTodosLosUsuarios()) { 
        // El nombre del nodo en JGraphT será el ID o nombre del usuario
        g.addVertex(u.getNombre()); 
    } 

    // 2. Añadir Aristas (Relaciones)
    // Itera sobre todos los usuarios para encontrar sus vecinos.
    for (Usuario origen : this.grafo.getTodosLosUsuarios()) { 
        
        for (Usuario destino : this.grafo.getVecinos(origen)) {            
            // Si la arista no existe, la añade
            g.addEdge(origen.getNombre(), destino.getNombre()); 
        }
    }
    
    // **********************************************
    
    // ... Resto del código de JGraphX (NO CAMBIAR) ...
    
    JGraphXAdapter<String, DefaultEdge> graphAdapter = new JGraphXAdapter<>(g);
    mxGraphComponent graphComponent = new mxGraphComponent(graphAdapter);
    graphComponent.setConnectable(false); 
    graphComponent.getGraph().setAllowDanglingEdges(false);

    // Aplica un layout para organizar los nodos en un círculo
    mxCircleLayout layout = new mxCircleLayout(graphAdapter);
    layout.execute(graphAdapter.getDefaultParent());

    // Añade el componente del grafo a la ventana
    getContentPane().setLayout(new BorderLayout());
    getContentPane().add(graphComponent, BorderLayout.CENTER);
    
    }
    /**
     * Creates new form VISUALGRAFO
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
